//! Golden decode-regression vectors (Task 8, decision 9c).
//!
//! Reads every WAV + `testdata/golden/manifest.toml` (generated by
//! `cargo run -p coppa-bench --release --example golden_vectors_gen`,
//! `crates/coppa-bench/examples/golden_vectors_gen.rs`) and asserts that
//! `CoppaTransceiver::receive` recovers each manifest entry's exact payload.
//! A future PHY/FEC change that silently breaks decoding of one of these
//! frozen, committed frames now fails a real, visible test -- not just a
//! full bench sweep nobody runs by default.
//!
//! ## Why this file lives here
//!
//! The task brief names `crates/coppa-protocol/tests/golden_vectors.rs`
//! explicitly, matching Cargo's standard per-crate integration-test
//! convention (any `.rs` directly under a crate's own `tests/` directory
//! becomes its own integration-test binary, run via
//! `cargo test -p coppa-protocol --test golden_vectors` or as part of
//! `cargo test --workspace`) -- this crate didn't have a `tests/` directory
//! before this task; this is the first file in it. This repo's OTHER
//! integration tests (`tests/phase_c_loopback.rs` etc.) instead live under
//! the repo-root `coppa` package's own `tests/` directory, because those
//! predate this task and exercise multiple crates' interaction generically;
//! this test is scoped tightly to `coppa-protocol`'s own `CoppaTransceiver`
//! decode path, so a per-crate `tests/` directory (Cargo's default
//! convention, not a repo-specific one) fits at least as well and is what
//! the brief asked for.

use std::path::{Path, PathBuf};

use coppa_bench::scenario::select_profile;
use coppa_codec::ofdm::CoppaProfile;
use coppa_protocol::modem::transceiver::CoppaTransceiver;

#[derive(serde::Deserialize)]
struct ManifestFile {
    vectors: Vec<VectorEntry>,
}

#[derive(serde::Deserialize)]
struct VectorEntry {
    id: String,
    level: u8,
    channel: String,
    #[allow(dead_code)]
    seed: u64,
    #[allow(dead_code)]
    seed_attempts: u64,
    payload_hex: String,
    wav_file: String,
    sample_rate: u32,
    expected_decode_ok: bool,
}

/// Golden-vector root directory, relative to this crate's own manifest dir.
fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../testdata/golden")
}

/// Mirrors `golden_vectors_gen.rs`'s `profile_for`: every level uses its normal
/// per-level routing (delegated to `coppa_bench::scenario::select_profile`, the
/// single source of truth for that rule -- levels 1-4 -> hf_standard, 5+ ->
/// vhf_wide) EXCEPT the `poor25` and `ssbcfo` channel conditions, which force
/// `hf_standard` for every level (an HF-multipath Watterson channel is not a
/// fair test of the VHF-routed profile's much shorter cyclic prefix, and the
/// SSB rig passband filter is an HF-specific impairment not applicable to the
/// VHF-routed profile's wider active band -- see that generator's module doc).
///
/// This pulls in `coppa-bench` as a dev-dependency of `coppa-protocol`, which
/// looks like it should be a cycle (`coppa-bench` depends on `coppa-protocol`
/// as a normal dependency) but isn't: Cargo resolves dev-dependency edges
/// separately from the normal dependency graph, since they're only needed to
/// build this crate's own tests/examples, not to build `coppa-protocol` itself
/// as a library -- verified directly (`cargo check -p coppa-protocol --tests`
/// and `cargo tree -p coppa-protocol -e dev` both resolve cleanly here).
fn profile_for(level: u8, channel: &str) -> CoppaProfile {
    if channel == "poor25" || channel == "ssbcfo" {
        return CoppaProfile::hf_standard();
    }
    select_profile(level)
}

fn decode_hex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd-length hex string: {s}");
    (0..s.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(&s[i..i + 2], 16).unwrap_or_else(|e| panic!("bad hex in {s}: {e}"))
        })
        .collect()
}

fn read_wav_f32(path: &Path) -> (Vec<f32>, u32) {
    let mut reader = hound::WavReader::open(path)
        .unwrap_or_else(|e| panic!("failed to open golden WAV {}: {e}", path.display()));
    let spec = reader.spec();
    assert_eq!(
        spec.bits_per_sample,
        16,
        "golden WAV {} is not 16-bit PCM",
        path.display()
    );
    assert_eq!(
        spec.sample_format,
        hound::SampleFormat::Int,
        "golden WAV {} is not integer PCM",
        path.display()
    );
    // Full-scale normalization, matching `coppa_audio::file_backend::WavSource::open`'s
    // `1i64 << (bits_per_sample - 1)` convention (32768 for 16-bit), not `i16::MAX` (32767).
    // The two differ only by a ~1/32768 amplitude scale -- not a correctness bug on its own
    // (this reader and `golden_vectors_gen.rs`'s writer were self-consistent either way), but
    // an unnecessary, undocumented divergence from house style.
    let max_val = (1i64 << (spec.bits_per_sample - 1)) as f32;
    let samples: Vec<f32> = reader
        .samples::<i16>()
        .map(|s| {
            s.unwrap_or_else(|e| panic!("bad sample in {}: {e}", path.display())) as f32 / max_val
        })
        .collect();
    (samples, spec.sample_rate)
}

#[test]
fn golden_vectors_decode_to_expected_payloads() {
    let dir = golden_dir();
    let manifest_path = dir.join("manifest.toml");
    let manifest_text = std::fs::read_to_string(&manifest_path).unwrap_or_else(|e| {
        panic!(
            "failed to read golden manifest {}: {e} (run `cargo run -p coppa-bench --release \
             --example golden_vectors_gen` from the workspace root to (re)generate it)",
            manifest_path.display()
        )
    });
    let manifest: ManifestFile =
        toml::from_str(&manifest_text).expect("failed to parse golden manifest.toml");

    assert!(
        !manifest.vectors.is_empty(),
        "golden manifest has no vectors"
    );

    let mut failures = Vec::new();

    for v in &manifest.vectors {
        let wav_path = dir.join(&v.wav_file);
        let (samples, sample_rate) = read_wav_f32(&wav_path);
        if sample_rate != v.sample_rate {
            failures.push(format!(
                "{}: sample rate mismatch (wav={sample_rate}, manifest={})",
                v.id, v.sample_rate
            ));
            continue;
        }

        let expected_payload = decode_hex(&v.payload_hex);
        let profile = profile_for(v.level, &v.channel);
        let tx = CoppaTransceiver::new(profile, 1);

        match tx.receive(&samples) {
            Ok((header, bytes, _rec_level)) => {
                if !v.expected_decode_ok {
                    failures.push(format!(
                        "{}: decoded successfully but manifest expected a decode failure",
                        v.id
                    ));
                    continue;
                }
                if header.speed_level != v.level {
                    failures.push(format!(
                        "{}: decoded header speed_level {} != manifest level {}",
                        v.id, header.speed_level, v.level
                    ));
                }
                let ok = bytes.len() >= expected_payload.len()
                    && bytes[..expected_payload.len()] == expected_payload[..];
                if !ok {
                    failures.push(format!(
                        "{}: recovered payload does not match manifest (recovered {} bytes, expected {})",
                        v.id,
                        bytes.len(),
                        expected_payload.len()
                    ));
                }
            }
            Err(e) => {
                if v.expected_decode_ok {
                    failures.push(format!("{}: expected clean decode but got {e:?}", v.id));
                }
            }
        }
    }

    assert!(
        failures.is_empty(),
        "golden vector failures ({}/{}):\n{}",
        failures.len(),
        manifest.vectors.len(),
        failures.join("\n")
    );
}

/// Sanity check: the manifest itself covers the full 5 levels x 4 channels = 20
/// grid the brief specifies (levels {1,2,5,6,9} x channels {clean, awgn12,
/// poor25, ssbcfo}), not a partial set some generator run happened to produce.
#[test]
fn golden_manifest_covers_the_full_grid() {
    let dir = golden_dir();
    let manifest_text = std::fs::read_to_string(dir.join("manifest.toml"))
        .expect("failed to read golden manifest.toml");
    let manifest: ManifestFile =
        toml::from_str(&manifest_text).expect("failed to parse golden manifest.toml");

    let levels = [1u8, 2, 5, 6, 9];
    let channels = ["clean", "awgn12", "poor25", "ssbcfo"];

    for &level in &levels {
        for &channel in &channels {
            assert!(
                manifest
                    .vectors
                    .iter()
                    .any(|v| v.level == level && v.channel == channel),
                "missing golden vector for level {level} / channel {channel}"
            );
        }
    }
    assert_eq!(
        manifest.vectors.len(),
        levels.len() * channels.len(),
        "manifest has unexpected extra/missing entries"
    );
}
