//! Host interfaces for Coppa.
//!
//! Provides a VARA-style TCP control protocol (not RF/waveform-compatible with VARA)
//! command/data port interface and optional WebSocket JSON API for web clients.

#[cfg(feature = "vara-tcp")]
pub mod vara;

#[cfg(feature = "websocket")]
pub mod websocket;

#[cfg(feature = "kiss-tnc")]
pub mod kiss;

/// A frame of data exchanged between host application and the Coppa engine.
#[derive(Debug, Clone)]
pub struct HostFrame {
    pub port: u8,
    pub data: Vec<u8>,
}

/// Events generated by host interfaces for the engine event loop.
#[derive(Debug, Clone)]
pub enum HostEvent {
    /// A new client connected.
    Connected { client_id: u32 },
    /// A client disconnected.
    Disconnected { client_id: u32 },
    /// Data received from a client.
    DataReceived { client_id: u32, data: Vec<u8> },
    /// A VARA command was received.
    VaraCommand { client_id: u32, command: String },
    /// Connection request (CONNECT callsign1 callsign2).
    ConnectRequest {
        client_id: u32,
        source: String,
        destination: String,
    },
    /// Disconnect request.
    DisconnectRequest { client_id: u32 },
}

/// Responses sent from the engine back to host clients.
#[derive(Debug, Clone)]
pub enum HostResponse {
    /// Decoded data to send back to a client.
    DataOut { client_id: u32, data: Vec<u8> },
    /// Status update for a client.
    StatusUpdate { client_id: u32, status: String },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_host_frame() {
        let frame = HostFrame {
            port: 0,
            data: vec![0x48, 0x65, 0x6C, 0x6C, 0x6F],
        };
        assert_eq!(frame.port, 0);
        assert_eq!(frame.data, b"Hello");
    }

    #[test]
    fn test_host_event_variants() {
        let event = HostEvent::Connected { client_id: 1 };
        match event {
            HostEvent::Connected { client_id } => assert_eq!(client_id, 1),
            _ => panic!("Wrong variant"),
        }
    }
}
