#ifndef COPPA_H
#define COPPA_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a Coppa engine instance.
 */
typedef struct CoppaHandle CoppaHandle;

/**
 * Opaque handle to a streaming decode session.
 *
 * `coppa_feed_samples` pushes samples directly into the engine's internal
 * `StreamingReceiver` (via `CoppaCore::push_samples`), which owns its own
 * ring/sync-detector/frame-boundary bookkeeping — no buffer growth cap or
 * rescanning is needed here, since the receiver never re-examines samples it's
 * already consumed and bounds its own memory (`2 * max_frame_samples`; see
 * `coppa_protocol::modem::streaming`).
 */
typedef struct CoppaStreamHandle CoppaStreamHandle;

/**
 * Create a new Coppa engine instance.
 *
 * Returns a pointer to the engine handle, or null on failure.
 * The caller must free the handle with [`coppa_engine_destroy`].
 */
 struct CoppaHandle *coppa_engine_create(void);

/**
 * Destroy a Coppa engine instance and free its resources.
 *
 * After this call, `*handle_ptr` is set to null. Calling with a null
 * `handle_ptr` or a `*handle_ptr` that is already null is a safe no-op.
 *
 * # Safety
 *
 * `handle_ptr` must be either null or a valid pointer to a variable that
 * holds a pointer returned by [`coppa_engine_create`].
 */
 void coppa_engine_destroy(struct CoppaHandle **handle_ptr);

/**
 * Get the library version string.
 *
 * Returns a pointer to a static null-terminated string. The caller must
 * not free or modify the returned pointer.
 */
 const char *coppa_version(void);

/**
 * Encode a message string to audio samples.
 *
 * On success, `out_samples` and `out_len` are populated with the sample
 * buffer and its length. The sample buffer must be freed with
 * [`coppa_free_samples`] using the exact length returned in `out_len`.
 *
 * Returns `-4` if the internal lock is poisoned, or `-5` if an internal
 * panic occurred. **After either of these errors the handle is permanently
 * broken** — destroy it with `coppa_engine_destroy` and create a new one.
 *
 * # Safety
 *
 * `handle` must be a valid engine handle. `message` must be a valid
 * null-terminated C string.
 */

int32_t coppa_encode(struct CoppaHandle *handle,
                     const char *message,
                     float **out_samples,
                     uintptr_t *out_len);

/**
 * Decode audio samples back to a message string.
 *
 * On success, `out_message` is populated with a pointer to a
 * null-terminated string that must be freed with [`coppa_free_string`].
 *
 * Returns `-4` if the internal lock is poisoned, or `-5` if an internal
 * panic occurred. **After either of these errors the handle is permanently
 * broken** — destroy it with `coppa_engine_destroy` and create a new one.
 *
 * # Safety
 *
 * `handle` must be a valid engine handle. `samples` must point to
 * `num_samples` valid f32 values.
 */

int32_t coppa_decode(struct CoppaHandle *handle,
                     const float *samples,
                     uintptr_t num_samples,
                     char **out_message);

/**
 * Free a sample buffer returned by `coppa_encode`.
 *
 * `len` **must** be the exact value that was written to `out_len` by
 * `coppa_encode`. Passing a different length is undefined behavior.
 * Zero-length buffers are valid and will be freed correctly.
 *
 * # Safety
 *
 * `samples` must be a pointer returned by `coppa_encode`, and `len` must
 * be the exact length returned alongside it in `out_len`.
 */
 void coppa_free_samples(float *samples, uintptr_t len);

/**
 * Free a string returned by `coppa_decode` or `coppa_get_decoded`.
 *
 * Uses `CString::from_raw` internally — no `strlen` rescan needed because
 * the `CString` already knows its own length from the original allocation.
 *
 * # Safety
 *
 * `s` must be a pointer returned by `coppa_decode` or `coppa_get_decoded`,
 * and must not have been freed already.
 */
 void coppa_free_string(char *s);

/**
 * Start a streaming decode session.
 *
 * Returns a handle to the stream, or null on failure.
 */
 struct CoppaStreamHandle *coppa_start_stream(void);

/**
 * Feed samples into a streaming decode session.
 *
 * Samples are pushed directly into the engine's `StreamingReceiver`, which
 * detects frame boundaries and demodulates each completed frame on its own —
 * the caller can feed any chunk size at any time; there is no minimum-samples
 * threshold to reach before a decode is attempted. Any frames the receiver
 * completes as a result of this call are queued for [`coppa_get_decoded`].
 *
 * Returns `-4` if the internal lock is poisoned, or `-5` if an internal
 * panic occurred. **After either of these errors the stream handle is
 * permanently broken** — destroy it with `coppa_stop_stream` and create
 * a new one.
 *
 * # Safety
 *
 * `handle` must be a valid stream handle. `samples` must point to
 * `num_samples` valid f32 values.
 */

int32_t coppa_feed_samples(struct CoppaStreamHandle *handle,
                           const float *samples,
                           uintptr_t num_samples);

/**
 * Get the next decoded message from a streaming session.
 *
 * Returns a pointer to a null-terminated string, or null if no messages
 * are available. The string must be freed with `coppa_free_string`.
 *
 * # Safety
 *
 * `handle` must be a valid stream handle.
 */
 char *coppa_get_decoded(struct CoppaStreamHandle *handle);

/**
 * Stop and destroy a streaming decode session.
 *
 * # Safety
 *
 * `handle` must be a valid stream handle returned by `coppa_start_stream`.
 */
 void coppa_stop_stream(struct CoppaStreamHandle *handle);

#endif  /* COPPA_H */
